spring:

  datasource:
    hikari:
      maximum-pool-size: 5 # 커넥션 풀이 모자라서 낙관적 락이 있어도 실패하는 경우 예방
    url: jdbc:mysql://localhost:3306/bank
    username: bank
    password: bank
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

